import type { Metadata } from "next";
import './globals.css'
import Script from 'next/script'
import '@fortawesome/fontawesome-svg-core/styles.css'
import '@/assets/css/main.css'

export const dynamic = 'force-dynamic';
export const revalidate = 10;


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        {/* Scripts */}
        <Script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" strategy='lazyOnload' />
        <Script src="/js/jquery.min.js" strategy='beforeInteractive' />
        <Script src="/js/browser.min.js" strategy='lazyOnload' />
        <Script src="/js/breakpoints.min.js" strategy='beforeInteractive' />
        <Script src="/js/util.js" strategy='lazyOnload' />
        <Script src="/js/main.js" strategy='afterInteractive' />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
